#!/bin/sh
all:
	rm -Rf ./html
	mkdir -p ./html
	phpdoc --directory ../Structures_CSS,./tutorials --target ./html --title "Structures_CSS Documentation" --output "HTML:frames" --defaultpackagename structures_css --defaultcategoryname structures --pear 
